Add spell checker project
CodeYourFuture/The-Piscine pull request #24
Opened 2024-11-12 23:53 UTC by 40thieves

## Changelist

Adds a spell checker project.

I expect this would be a solo project - at least as it stands - but welcome feedback on extensions etc. I initially thought this might be a bit bigger in scope, but many of the interesting aspects of this project are in asking questions about their approach (e.g. "what might happen if you replaced Basic English with real English?"), and I think those are difficult to write a very precise rubric like I think we're aiming for here. Having said that I still think this is a decent standalone project.

2024-11-26 11:08 UTC, SallyMcGrath requested changes
Nice! Simple

It doesn't ask for tests. I think we probably want something, even just console.asserts?

2024-11-26 11:08 UTC, SallyMcGrath commented on Project-Spell-Checker/README.md
> +- "Incorrect" words (i.e. those not found in the Basic English word list) that are adjacent to punctuation characters should still be marked as spelling mistakes
- The website scores 100 for Accessibility on Lighthouse.

2024-12-03 21:39 UTC, 40thieves commented
Not sure how I missed the testing & lighthouse points, but have now copied them over. Agree that they are both requirements that we want.

2024-12-04 18:03 UTC, illicitonion reviewed
I just did this project, it's cute, but assuming we're not requiring re-styling input to show invalid words, it feels a little simple? My implementation is ~20 lines of ~trivial code.

If we _are_ requiring re-styling input... That's an interesting, but quite _big_ challenge...

2025-01-08 14:20 UTC, illicitonion commented
>> If we are requiring re-styling input... That's an interesting, but quite big challenge...
>
> I think this is probably over the line of complexity - it's a surprisingly difficult task, often even for quite senior folks!

Agreed!

> I think we touched on this on a call and my memory is that it sounded like you had some ideas about ramping up the difficulty a bit? (Or possibly could have been Sally?)

I think off the top of my head possible extensions were...
* Adding custom words to the dictionary (and re-evaluating the check)
* Suggesting possible replacement words (possibly with some scaffolding, e.g. we could provide a `calculateLevenshteinDistance` function or something and just expect the trainees to use it)
* Handling punctuation more interestingly (e.g. in-word punctuation, maybe handling hyphenated words as two independent words, passing "blue-green" because both "blue" and "green" are words)
* Special-casing capitalised words assuming they're names ("I went to lunch with Ali" passes even though "ali" isn't in the dictionary)

They're all reasonably minor additions/tweaks, but maybe all of them together equal a reasonable individual project?

2025-01-15 22:54 UTC, 40thieves commented
Pushed a few commits - I've added all of the suggestions except the replacement words. I feel like this might be enough?

Providing `calculateLevenshteinDistance` is interesting but I think this really only adds the challenge of some DOM manipulation?

2025-01-16 11:21 UTC, illicitonion approved these changes
Looks great! :shipit:

2025-01-16 11:21 UTC, illicitonion commented on Project-Spell-Checker/README.md
> +If a misspelled word is detected, there should be a way for the user to add that word to the dictionary. The spell check should then be triggered again, and the word that was added to the dictionary
```suggestion
If a misspelled word is detected, there should be a way for the user to add that word to the dictionary. The spell check should then be triggered again, and the word that was added to the dictionary should no longer be considered a misspelled word (so should _not_ be highlighted). **Note**: the custom dictionary does _not_ need to be saved, so reloading the page can reset back to the initial dictionary.
```

2025-01-16 23:11 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +When the spell check is triggered, your website should check every word that the user has typed to see if it exists in the Basic English word list that we have provided (in `words.json`).
This is something of a good point, but... other than the Days Calendar project, I don't see another example of defining how helper files should be imported. Days Calendar is a bit of an exception too as it's importing across web and Node.

So I guess my question is whether we should go through and add instructions throughout all the projects.

2025-01-16 23:17 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +If there are any words that aren't in the Basic English word list, you should consider those words as a spelling mistake. All spelling mistakes should be presented to the user underneath the input, a
Hmm, good question - I think I was thinking that the text underneath would be sufficient. I think I added the point about highlighting on the idea that the text underneath would be styled to indicate that it was an error (i.e. red, possibly underlining). As discussed below, I think highlighting the word in the input would be much more difficult.

And I will admit "highlighting" is a useful verb to shorthand "mark as misspelled".

2025-01-16 23:29 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +If there are any words that aren't in the Basic English word list, you should consider those words as a spelling mistake. All spelling mistakes should be presented to the user underneath the input, a
Pushed a commit to try improve this.

2025-01-16 23:30 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +- It should be obvious to the user that there is a spelling mistake, both with visuals and some explanatory text
Good point. Pushed a commit which suggests leaving it blank (I'm thinking about the UX of a "real" spell checker - which usually doesn't explicitly say anything if there's no misspellings)

2025-01-16 23:33 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +When the spell check is triggered, your website should check every word that the user has typed to see if it exists in the Basic English word list that we have provided (in `words.json`).
Actually... now that I think about it, this may fall under the same situation as Days Calendar as (assuming ESM) it'll need a import type assertion.

I need to drop off now, but will try to get to this tomorrow.

2025-01-16 23:34 UTC, 40thieves commented
I realised tonight there were more comments I'd missed previously so have pushed a couple more commits to address those.

There's 1 outstanding point about importing a JSON file (plus a general question about importing in these projects), but I'll have to get to that tomorrow.

2025-01-17 11:19 UTC, illicitonion commented on Project-Spell-Checker/README.md
> +When the spell check is triggered, your website should check every word that the user has typed to see if it exists in the Basic English word list that we have provided (in `words.json`).
Yeah, I think either we want to provide a `.js` file which contains a function to get the data (which can just be trivially `<script>` included), or an example page that does something like output the count of words or something :)

(Happy to remove these bits of scaffolding when we teach more ESM in ITP, but right now we're pretty light on it...)

2025-01-25 13:22 UTC, 40thieves commented
@SallyMcGrath I don't suppose you have a chance to review this today? I'm strongly tempted to (ab)use my admin privs here, since I think I've addressed your points.

2025-01-25 13:22 UTC, 40thieves commented on Project-Spell-Checker/README.md
> +When the spell check is triggered, your website should check every word that the user has typed to see if it exists in the Basic English word list that we have provided (in `words.json`).
I think I'll look to merge this and follow up with changes for all project in a separate PR.

2025-01-25 13:23 UTC, 40thieves commented
Nvm, it was blocking the review only because I had an outstanding comment to address. Will merge now.

2025-01-25 13:23 UTC, merged